apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reshet-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/guyhguy25/argocd-reshet
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true