apiVersion: apps/v1
kind: Deployment
metadata:
  name: reshet-dev
  namespace: dev
  labels:
    app: reshet-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reshet-dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: reshet-dev
    spec:
      containers:
      - name: reshet-dev
        image: guyhaguy/reshet-web:4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 15
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3003"
        - name: HOSTNAME
          value: "0.0.0.0"