apiVersion: v1
kind: Service
metadata:
  name: reshet-dev
  labels:
    app: reshet-dev
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app: reshet-dev